# Production configuration
%prod.quarkus.datasource.db-kind=postgresql
%prod.quarkus.datasource.username=${DATASOURCE_USERNAME}
%prod.quarkus.datasource.password=${DATASOURCE_PASSWORD}
%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/task-management-service-db
%prod.quarkus.datasource.jdbc.max-size=16
%prod.quarkus.hibernate-orm.database.generation=validate


# Dev configuration
%dev.quarkus.hibernate-orm.database.generation=drop-and-create


# Test configuration
%test.quarkus.hibernate-orm.database.generation=drop-and-create
%test.quarkus.datasource.deveservices.enabled=true
%test.quarkus.datasource.db-kind=postgresql
