# API prefix
quarkus.rest.path=/api

# Common database configuration
quarkus.datasource.db-kind=postgresql
quarkus.hibernate-orm.database.generation=none
quarkus.flyway.migrate-at-start=true

# Production configuration
%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://db:5432/task-management-service-db
%prod.quarkus.datasource.jdbc.max-size=8
%prod.quarkus.datasource.username=${DATASOURCE_USERNAME}
%prod.quarkus.datasource.password=${DATASOURCE_PASSWORD}

# Dev configuration
%dev.quarkus.datasource.devservices.enabled=true

# Test configuration
%test.quarkus.datasource.devservices.enabled=true
%test.quarkus.flyway.clean-at-start=true

# Container image build configuration
quarkus.native.container-build=true
quarkus.container-image.build=true
quarkus.container-image.registry=docker.io
quarkus.container-image.group=jabirminjibir
quarkus.container-image.name=task-management-service
quarkus.container-image.tag=latest

# Keep the Swagger UI accessible in Production.
# This is considered security risk for production environments.
quarkus.swagger-ui.always-include=true
